/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/kubernetes-sigs/service-catalog/pkg/apis/servicecatalog/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeExtensionRequests implements ExtensionRequestInterface
type FakeExtensionRequests struct {
	Fake *FakeServicecatalogV1beta1
	ns   string
}

var extensionrequestsResource = schema.GroupVersionResource{Group: "servicecatalog.k8s.io", Version: "v1beta1", Resource: "extensionrequests"}

var extensionrequestsKind = schema.GroupVersionKind{Group: "servicecatalog.k8s.io", Version: "v1beta1", Kind: "ExtensionRequest"}

// Get takes name of the extensionRequest, and returns the corresponding extensionRequest object, and an error if there is any.
func (c *FakeExtensionRequests) Get(name string, options v1.GetOptions) (result *v1beta1.ExtensionRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(extensionrequestsResource, c.ns, name), &v1beta1.ExtensionRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ExtensionRequest), err
}

// List takes label and field selectors, and returns the list of ExtensionRequests that match those selectors.
func (c *FakeExtensionRequests) List(opts v1.ListOptions) (result *v1beta1.ExtensionRequestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(extensionrequestsResource, extensionrequestsKind, c.ns, opts), &v1beta1.ExtensionRequestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.ExtensionRequestList{ListMeta: obj.(*v1beta1.ExtensionRequestList).ListMeta}
	for _, item := range obj.(*v1beta1.ExtensionRequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested extensionRequests.
func (c *FakeExtensionRequests) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(extensionrequestsResource, c.ns, opts))

}

// Create takes the representation of a extensionRequest and creates it.  Returns the server's representation of the extensionRequest, and an error, if there is any.
func (c *FakeExtensionRequests) Create(extensionRequest *v1beta1.ExtensionRequest) (result *v1beta1.ExtensionRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(extensionrequestsResource, c.ns, extensionRequest), &v1beta1.ExtensionRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ExtensionRequest), err
}

// Update takes the representation of a extensionRequest and updates it. Returns the server's representation of the extensionRequest, and an error, if there is any.
func (c *FakeExtensionRequests) Update(extensionRequest *v1beta1.ExtensionRequest) (result *v1beta1.ExtensionRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(extensionrequestsResource, c.ns, extensionRequest), &v1beta1.ExtensionRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ExtensionRequest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeExtensionRequests) UpdateStatus(extensionRequest *v1beta1.ExtensionRequest) (*v1beta1.ExtensionRequest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(extensionrequestsResource, "status", c.ns, extensionRequest), &v1beta1.ExtensionRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ExtensionRequest), err
}

// Delete takes name of the extensionRequest and deletes it. Returns an error if one occurs.
func (c *FakeExtensionRequests) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(extensionrequestsResource, c.ns, name), &v1beta1.ExtensionRequest{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeExtensionRequests) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(extensionrequestsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.ExtensionRequestList{})
	return err
}

// Patch applies the patch and returns the patched extensionRequest.
func (c *FakeExtensionRequests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.ExtensionRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(extensionrequestsResource, c.ns, name, pt, data, subresources...), &v1beta1.ExtensionRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ExtensionRequest), err
}
